### ISSUE TITLE
总是发送失败问题

### ISSUE THREAD

**Issue by ListenQ** [uyoufu/UZonMail#35]
![image](https://github.com/user-attachments/assets/43aa047b-ef7d-4098-8a2a-71621f29accc)

![img_v3_02g7_7d294614-58b5-4c84-ac97-04f4ac813f0g](https://github.com/user-attachments/assets/a047265f-1f5b-4d80-9ce9-7e824f39f1d2)

![image](https://github.com/user-attachments/assets/d94a7786-4d5f-4d88-b517-b5940e95d34d)

发送邮件相同的内容和收发件人，但是时成功时失败，在次发送则是全失败

**Comment by ListenQ** [comment]
![img_v3_02g7_72b1a8c6-a293-443c-8a27-1dcd5db8e86g](https://github.com/user-attachments/assets/ad89af58-6c1d-474b-84ec-4f43a6567a66)

还有这种错误的时候，关闭软件重新打开进去发送邮件，出现全失败，而且都提升这个错误

**Comment by uyoufu** [comment]
应该是你发件频率太高了，smtp 发件频率有限制的，比如 qq，每分钟最多发 15 封左右。
可以在设置中，设置发件间隔来减小发件速度
